name: face_app_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #this line is added for localization
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #  assets:
  #    - assets/icons/
  #    - assets/images/
  #    - assets/trainned_model/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  #  fonts:
  #    - family: MainFont
  #      fonts:
  #        - asset: assets/font/Segoe UI.ttf
  #        - asset: assets/font/Segoe UI Bold.ttf
  #        - asset: assets/font/Segoe UI Bold Italic.ttf
  #        - asset: assets/font/Segoe UI Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
